#!/usr/bin/env python3
"""Regenerate lib/report-prompts.ts from scripts/prompt_templates.py."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from prompt_templates import (  # noqa: E402
    CONTEXT_BLOCK,
    LENGTH_BY_DESCRIPTION,
    PERSONA,
    PROMPTS_BY_DESCRIPTION,
    USER_BLOCK,
    output_rules,
)

OUT = ROOT / "lib" / "report-prompts.ts"

DOC = """/**
 * Prompt templates for AI report sections.
 * AUTO-GENERATED by scripts/sync-report-prompts-ts.py — edit prompt_templates.py instead.
 */

export const PROMPT_VARIABLES_DOC = {
  birth_date: "YYYY-MM-DD",
  birth_time: "HH:mm (24h)",
  gender: "male | female",
  sexuality: "affects love/attraction chapters",
  job_status: "employed | unemployed | self_employed",
  four_pillars: "Year month day hour pillars",
  day_master: "Day stem (核心元素)",
  day_master_strength: "weak | balanced | strong",
  five_elements: "五行 balance summary",
  ten_gods_summary: "個性與能力重點",
  hidden_stems: "地支藏干",
  major_luck_current: "Current 大運",
  major_luck_next: "Next 大運",
  current_age: "Integer age",
  current_year: "Gregorian year",
  current_year_stem_branch: "流年",
  favorable_elements: "用神",
  unfavorable_elements: "忌神",
  relationship_status: "single | partnered",
} as const;

"""


def esc(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    lines = [
        DOC,
        f"const PERSONA = {esc(PERSONA)};",
        "",
        f"const USER_BLOCK = {esc(USER_BLOCK)};",
        "",
        f"const CONTEXT_BLOCK = {esc(CONTEXT_BLOCK)};",
        "",
        "function outputRules(desc: string): string {",
        "  const ranges: Record<string, [number, number]> = {",
    ]
    for k, (lo, hi) in sorted(LENGTH_BY_DESCRIPTION.items()):
        lines.append(f"    {json.dumps(k, ensure_ascii=False)}: [{lo}, {hi}],")
    lines.extend(
        [
            "  };",
            "  const [lo, hi] = ranges[desc] ?? [400, 700];",
            "  const mid = Math.round((lo + hi) / 2);",
            '  return `【輸出要求 — 字數硬限制】\\n- 只輸出內文段落，不要標題、不要 JSON、不要 markdown\\n- 全文字數必須在 ${lo}–${hi} 字之間（目標約 ${mid} 字）；超過 ${hi} 字視為不合格\\n- 只寫「本篇要寫什麼」的單一主題，禁止寫其他章節（例如本篇講能力就不要寫感情、大運、年齡建議）\\n- 2–3 段即可，段間空一行；不要用「總之」「綜上所述」收尾\\n- 勿輸出英文欄位值（如 self_employed），工作狀態用中文（上班族／求職中／自己做生意）`;',
            "}",
            "",
            "/** Key = exact `description` field from JSON (AI entries). */",
            "export const PROMPTS_BY_DESCRIPTION: Record<string, string> = {",
        ]
    )
    for desc, prompt in PROMPTS_BY_DESCRIPTION.items():
        lines.append(f"  {json.dumps(desc, ensure_ascii=False)}: {esc(prompt)},")
    lines.extend(
        [
            "};",
            "",
            "export function getPromptForEntry(description: string): string | undefined {",
            "  return PROMPTS_BY_DESCRIPTION[description];",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(PROMPTS_BY_DESCRIPTION)} prompts)")


if __name__ == "__main__":
    main()
